version: '3.8'

services:
  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.flaskenv.docker
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sqlalchemy
      - POSTGRES_PASSWORD=sqlalchemy
      - POSTGRES_DB=sqlalchemy_dev
    ports:
      - 8032:5432

volumes:
  postgres_data: