version: '3.8'

services: 
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sqlalchemy
      - POSTGRES_PASSWORD=sqlalchemy
      - POSTGRES_DB=sqlalchemy_dev
    ports:
      - 8032:5432

volumes:
  postgres_data: